id = "typst"
name = "Typst"
description = "Typst support."
version = "0.1.0"
schema_version = 1
authors = ["WeetHet <stas.ale66@gmail.com>"]
repository = "https://github.com/weethet/typst.zed"

[language_servers.tinymist]
name = "Typst language support"
language = "Typst"

[grammars.typst]
repository = "https://github.com/uben0/tree-sitter-typst"
commit = "abe60cbed7986ee475d93f816c1be287f220c5d8"
